- hosts: all
  tasks: 
    - name: check for docker
      shell: "service docker status"
      register: docker_verify
      ignore_errors: yes    

    - name: docker repo
      copy: src=./docker.repo dest=/etc/yum.repos.d/docker.repo

    - name: Install
      yum: name=docker-engine-1.12.1-1.el7.centos state=latest
      when: docker_verify.rc != 0
   
    - name: docker config
      copy: src=docker.config dest=/lib/systemd/system/docker.service

    - name: install utils
      yum: name={{item}} state=latest
      with_items:
       - nano 

    - name: restart services
      service: name={{item}} state=started enabled=true
      with_items:
       - docker

    - name: create docker group
      group: name=docker state=present

    - name: add user
      user: name=vagrant group=docker

- hosts: swarm-master
  tasks:
    - name: start swarm
      shell: docker swarm init --listen-addr 0.0.0.0:2377 --advertise-addr 192.0.3.11 
      ignore_errors: yes

- hosts: swarm-node
  tasks:
    - name: leave swarm
      shell: docker swarm leave
      ignore_errors: yes

    - name: join swarm
      shell: docker swarm join 192.0.3.11:2377
